site_name: Morgan Roberts
site_url: https://morganjroberts.github.io/portfolio/
repo_url: https://github.com/morganjroberts/portfolio

# MAKE SURE ALL FILES FOLLOW HYPENATED CONVENTION

nav:
    - Home: index.md
    - Open Source Ultrasound Imaging: open-source-ultrasound.md
    - Mechanical Engineering:
        - Transducer Manufacture: transducer-manufacture.md
        - Ultrasound Scanning System: ultrasound-scanning-system.md
        - Materials Characterisation Tank: materials-tank.md
        - MRI Hardware: mri-hardware.md 
    - Electrical Engineering:
        - Custom 128 Channel Interconnect: dl5-interconnect.md
        - Stepper Motor Controller: stepper-motor-control.md
        - Electrical Impedance Matching Network Design: matching-networks.md        
    - Software Development:
        - Medical Image Reconstruction Software: image-reconstruction-software.md
        - Instrument Control: instrument-control.md
    - Ultrasound Transducer Characterisation: transducer-characterisation.md
    - Material Development:
        - Ultrasound Imaging: ultrasound-phantoms.md
        - Dielectric Properties: dielectric-properties.md
    - Publications: publications.md
    - Personal: 
        - Kilns: kilns.md
        - Furniture: furniture.md
        - Investment Casting: investment-casting.md
        - Alarm Clock: alarm.md
    - CV: cv.md
    - Contact: contact.md

# extra_javascript: 
#     - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# markdown_extensions:
#     - mdx_math

theme: 
    name: material
    #logo: img/open-UST_logo.png
